### ISSUE TITLE
Howdy Rathore discussion thread

### ISSUE THREAD

**Issue by channikhabra** [JsChannel-Community/Idea-Box#3]
Please keep the discussion related to [Howdy Rathore](https://github.com/JsChannel-Community/Idea-Box/blob/master/Howdy_Rathre-Slack-bot.org) to this thread.

**Comment by schatten** [comment]
Github has a chat bot called [hubot][1]. Hubot was developed to work with Campfire, but has been extended to work with other chat systems including slack. We could create a deployment of hubot and start from there.

[1]: https://hubot.github.com/

**Comment by channikhabra** [comment]
That's interesting. I didn't know of hubot. Thanks man!

Hubot-scripts provide a great (and standard) way for other members to collaborate and contribute their ideas. Seems like the way to go. We can make a minimal bot for welcoming new members for v1, and if it works out, we can make it the official jschannel bot and add more hubot scripts. 

I'll create a repository for howdy-rathore and push soon. I've also added you to this organisation. Welcome aboard!

**Comment by samarpanda** [comment]
:+1:

**Comment by channikhabra** [comment]
Howdy-Rathore is being under development at: https://github.com/JsChannel-Community/Howdy-Rathore All the discussion regarding howdy-rathore shall be done in this repository's issues section.
